name: "Watchlistarr"
description: "Synchronise la Watchlist Plex vers Radarr et Sonarr"
version: "1.0.0"
slug: "watchlistarr"
arch:
  - aarch64
  - amd64
  - armv7
init: false
startup: services
boot: auto
ingress: true
ingress_port: 9000
panel_icon: mdi:movie-sync
map:
  - config:rw
options:
  LOG_LEVEL: "info"
  PORT: 9000
  PLEX_TOKEN: ""
  PLEX_SERVER: ""
  RADARR_URL: ""
  RADARR_API_KEY: ""
  SONARR_URL: ""
  SONARR_API_KEY: ""
  INTERVAL: 30
schema:
  LOG_LEVEL: str
  PORT: int
  PLEX_TOKEN: str
  PLEX_SERVER: str
  RADARR_URL: str
  RADARR_API_KEY: str
  SONARR_URL: str
  SONARR_API_KEY: str
  INTERVAL: int
